### PR TITLE
Add missing Verison and Repo Metadata

### PR DESCRIPTION
**Pull request by askpatrickw**
add the dunders

### CODE REVIEW

**Comment by askpatrickw** [comment]
As requested, @ladyada pls review\merge

**Comment by ladyada** [comment]
lgtm - can you do the PR against adafruit's version too?

**Review by ladyada — APPROVED** [review]

**Comment by askpatrickw** [comment]
🤦

**Comment by askpatrickw** [comment]
no  need to PR to myself

**Pull request closed without merging**
